eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gaojling/scdemo
          searchPaths: scconfigfile
    bus:
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
      enabled: true
    rabbitmq:
      host: localhost
      port: 5672
      username: locate
      password: locate
  application:
    name: config-server
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-headers: "*"
