server:
  port: 8761

eureka:
  instance:
    hostname: localhost
### registerWithEureka=false & fetchRegistry=false means euraka server
client:
  registerWithEureka: false
  fetchRegistry: false
  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/